* Research Programming
This course is ran in the Department of Theoretical Physics and Applied Mathematics in the University of
Cambridge. To run and do the exercises, you need access to a desktop/server at either DAMTP or DPMMS or a
computer system with =petsc4py=, =ipyparallel=, parallel =hdf5=, =matplotlib=, an OpenMP compiler and runtime,
=MPI=, and of course =git=. The DAMTP and DPMMS desktops and servers have all of these.

Some familiarity with the unix shell is also necessary.

** Github
You will also need a github account to do some of the exercises: just accessing the material is possible
without an account, but as some exercises require modifying a repository, an account is needed. Please surf to
https://www.github.com/ if you don't have an account yet.

* Getting the Course Material
- all the course material is available in a git repository — naturally
- the repo to clone is https://github.com/juhaj/damtp-research-programming
- some instructions on using the course repo
  - after cloning, make your own branch: =git branch mybranch=
  - check it out: =git checkout mybranch=
  - whatever you do, you do on this branch to avoid complications later
  - when you want the next lecture's material, do: =git checkout master= and =git pull=
  - you now have two options: merge =master= to =mybranch= or lose your changes to =mybranch=
  - merge: =git checkout mybranch= followed by =git merge master=, you need to sort your conflicts
  - lose local changes: =git checkout -f master=, =git pull=, and =git checkout -B mybranch master=
  - go back to doing whatever you do
  - note:
    - you do not have write access to the github repo so you cannot push
    - but you cannot screw up anything else than your local copy either so safe to play around if you wish
